name: Build 3 Apps
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Create Android folder in temp
        run: |
          cd /tmp
          flutter create --project-name farah temp_project
          cp -r /tmp/temp_project/android $GITHUB_WORKSPACE/

      - run: flutter pub get
      - run: dart run flutter_launcher_icons

      - name: Build Customer App
        run: |
          flutter build apk --release --target=lib/main_customer.dart
          cp build/app/outputs/flutter-apk/app-release.apk build/customer.apk

      - name: Build Client App
        run: |
          flutter build apk --release --target=lib/main_client.dart
          cp build/app/outputs/flutter-apk/app-release.apk build/client.apk

      - name: Build Admin App
        run: |
          flutter build apk --release --target=lib/main_admin.dart
          cp build/app/outputs/flutter-apk/app-release.apk build/admin.apk

      - uses: actions/upload-artifact@v4
        with:
          name: farah-apps
          path: |
            build/customer.apk
            build/client.apk
            build/admin.apk
